package drimer.drimain.config;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.context.event.ApplicationReadyEvent;
import org.springframework.context.event.EventListener;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;

@Component
@RequiredArgsConstructor
@Slf4j
public class AnnouncementSchemaInitializer {

    private final JdbcTemplate jdbcTemplate;

    @EventListener(ApplicationReadyEvent.class)
    public void ensureAnnouncementSchema() {
        // Idempotent fallback for environments where Flyway is disabled
        // or where older local H2 files missed V37 changes.
        run("ALTER TABLE announcements ADD COLUMN IF NOT EXISTS target_type VARCHAR(20) DEFAULT 'ALL' NOT NULL");
        run("ALTER TABLE announcements ADD COLUMN IF NOT EXISTS target_dzial_id BIGINT");

        run("CREATE TABLE IF NOT EXISTS announcement_target_users (" +
                "announcement_id BIGINT NOT NULL, " +
                "user_id BIGINT NOT NULL, " +
                "PRIMARY KEY (announcement_id, user_id), " +
                "CONSTRAINT fk_announcement_target_users_announcement " +
                "FOREIGN KEY (announcement_id) REFERENCES announcements(id) ON DELETE CASCADE, " +
                "CONSTRAINT fk_announcement_target_users_user " +
                "FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE" +
                ")");

        run("CREATE TABLE IF NOT EXISTS announcement_attachments (" +
                "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                "announcement_id BIGINT NOT NULL, " +
                "original_filename VARCHAR(500) NOT NULL, " +
                "stored_filename VARCHAR(255) NOT NULL UNIQUE, " +
                "content_type VARCHAR(255), " +
                "file_size BIGINT, " +
                "created_at TIMESTAMP NOT NULL, " +
                "created_by VARCHAR(255), " +
                "CONSTRAINT fk_announcement_attachments_announcement " +
                "FOREIGN KEY (announcement_id) REFERENCES announcements(id) ON DELETE CASCADE" +
                ")");

        run("CREATE INDEX IF NOT EXISTS idx_announcements_target_dzial_id ON announcements(target_dzial_id)");
        run("CREATE INDEX IF NOT EXISTS idx_announcement_attachments_announcement_id ON announcement_attachments(announcement_id)");

        log.info("[ANNOUNCEMENTS] Schema compatibility check completed.");
    }

    private void run(String sql) {
        try {
            jdbcTemplate.execute(sql);
        } catch (Exception ex) {
            log.warn("[ANNOUNCEMENTS] Schema statement skipped/failed: {} | reason: {}", sql, ex.getMessage());
        }
    }
}

