name: drimain_mobile
description: Mobilna wersja aplikacji driMain
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.0
  dio: ^5.4.0
  flutter_secure_storage: ^9.0.0
  intl: ^0.19.0
  collection: ^1.18.0
  font_awesome_flutter: ^10.7.0
  google_fonts: ^6.2.1
  image_picker: ^1.0.7
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png