name: drimain_frontend
description: "Drimain Flutter Web frontend"
publish_to: "none"

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dio: ^5.4.3+1
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.7
  intl: ^0.19.0
  flutter_secure_storage: ^9.2.2
  collection: ^1.18.0
  font_awesome_flutter: ^10.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^5.0.0

flutter:
  uses-material-design: true