version: "3.8"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-drimain}
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME:-drimain}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD:-drimain}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB:-drimain}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME:-drimain}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD:-drimain}
      JWT_SECRET: change_me_in_env
      JWT_ACCESS_TTL_MS: 900000
      JWT_REFRESH_TTL_MS: 604800000
      CORS_ALLOWED_ORIGINS: ""
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data: