version: '3.8'

services:
  db:
    image: postgres:15
    container_name: drimain-postgres
    environment:
      POSTGRES_DB: drimain
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

  app:
    build: .
    container_name: drimain-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/drimain
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_PROFILES_ACTIVE: default
    ports:
      - "8080:8080"
    volumes:
      - app_uploads:/app/uploads

volumes:
  postgres_data:
  app_uploads: