-- Flyway migration: create notifications table
-- Compatible with H2 and PostgreSQL (uses IDENTITY)
CREATE TABLE notifications (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT,
    module VARCHAR(255),
    type VARCHAR(50),
    title VARCHAR(255),
    message VARCHAR(2000),
    link VARCHAR(512),
    created_at TIMESTAMP,
    is_read BOOLEAN DEFAULT FALSE
);

-- Optional FK to users (set null on delete)
ALTER TABLE notifications
    ADD CONSTRAINT fk_notifications_user FOREIGN KEY (user_id)
    REFERENCES users(id) ON DELETE SET NULL;

CREATE INDEX idx_notifications_module ON notifications(module);
CREATE INDEX idx_notifications_created_at ON notifications(created_at);

