-- Flyway migration: create notifications table (idempotent)
CREATE TABLE IF NOT EXISTS notifications (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT,
    module VARCHAR(255),
    type VARCHAR(50),
    title VARCHAR(255),
    message VARCHAR(2000),
    link VARCHAR(512),
    created_at TIMESTAMP,
    is_read BOOLEAN DEFAULT FALSE
);

-- Add FK only if it does not already exist
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE constraint_name = 'fk_notifications_user'
          AND table_name = 'notifications'
    ) THEN
        ALTER TABLE notifications
            ADD CONSTRAINT fk_notifications_user
            FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_notifications_module ON notifications(module);
CREATE INDEX IF NOT EXISTS idx_notifications_created_at ON notifications(created_at);
