CREATE TABLE IF NOT EXISTS direct_messages (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    sender_id BIGINT NOT NULL,
    recipient_id BIGINT NOT NULL,
    content VARCHAR(2000) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    read_at TIMESTAMP,
    CONSTRAINT fk_direct_messages_sender FOREIGN KEY (sender_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_direct_messages_recipient FOREIGN KEY (recipient_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_direct_messages_sender_recipient_created
    ON direct_messages(sender_id, recipient_id, created_at);

CREATE INDEX IF NOT EXISTS idx_direct_messages_recipient_sender_read
    ON direct_messages(recipient_id, sender_id, read_at);

CREATE TABLE IF NOT EXISTS announcements (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title VARCHAR(255) NOT NULL,
    content VARCHAR(4000) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    created_by_user_id BIGINT,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_announcements_created_by FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_announcements_active_created
    ON announcements(active, created_at);

